#!/usr/bin/env node

const template = require("./template");

template(
  process.env.NODE_ENV || "production",
  (serverCompiler, serverConfig) => {
    serverCompiler.run((error, stats) => {
      if (error || stats.hasErrors()) {
        process.exitCode = 1;
      }
    });
  }
);
