#!/usr/bin/env node

const template = require("./template");

template("development", (serverCompiler) => {
  const nodemon = require("nodemon");
  const once = require("ramda").once;

  const startServer = () => {
    const serverPaths = Object.keys(serverCompiler.options.entry).map((entry) =>
      path.join(serverCompiler.options.output.path, `${entry}.js`)
    );
    nodemon({
      script: serverPaths[0],
      watch: serverPaths,
      nodeArgs: process.argv.slice(2),
    }).on("quit", process.exit);
  };

  const startServerOnce = once((err, stats) => {
    if (err) return;
    startServer();
  });
  serverCompiler.watch(serverConfig.watchOptions || {}, startServerOnce);
});
